package com.flex.adapter.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.flex.adapter.model.ErpAssembly;

@Repository
public interface ErpAssemblyRepository extends JpaRepository<ErpAssembly, Integer> { 
	
	@Query(value="select ewi_assembly_part_id,assembly_number,assembly_revision,created_date from ( select row_number() over ( order by  ap1.updated_date desc ) as myRow, ap1.ewi_assembly_part_id, ap1.assembly_number, ap1.assembly_revision, ap1.created_date from tbl_ewi_assembly_part ap1 inner join ( select distinct ap.ewi_assembly_part_id, ap.assembly_number from tbl_ewi_assembly_part ap left join tbl_ewi_work_instruction wi on ap.ewi_assembly_part_id =  wi.ewi_assembly_part_id where (lifecycle_phase is null or upper(lifecycle_phase) != 'OBSOLETE') and (effective_date is null or (to_char((effective_date at time zone 'America/Los_Angeles'),'YYYYMMDD')  <= to_char((current_timestamp at time zone 'America/Los_Angeles'),'YYYYMMDD'))) and (obsolete_date is null or (to_char((obsolete_date at time zone 'America/Los_Angeles'),'YYYYMMDD')  >= to_char((current_timestamp at time zone 'America/Los_Angeles'),'YYYYMMDD'))) and upper(ap.active_flag) != 'N' and ap.notification_type='EPI' and ap.customer_id = :customerId and ap.assembly_number like  :assemblyNumber and ap.erp_company_id = :erpCompanyId ) assy on ap1.ewi_assembly_part_id = assy.ewi_assembly_part_id ) where myRow between :startRecord and :maxNumberRecords", nativeQuery = true)
	List<ErpAssembly> getProcessInstructionAssembliesListByFilter(@Param("assemblyNumber") String assemblyNumber,@Param("erpCompanyId") int erpCompanyId,@Param("customerId") int customerId,@Param("startRecord") int startRecord,@Param("maxNumberRecords") int maxNumberRecords);
//	//@Query(value="select ewi_assembly_part_id,assembly_number,assembly_revision,created_date from ( select row_number() over ( order by  ap1.updated_date desc ) as myRow, ap1.ewi_assembly_part_id, ap1.assembly_number, ap1.assembly_revision, ap1.created_date from tbl_ewi_assembly_part ap1 inner join ( select distinct ap.ewi_assembly_part_id, ap.assembly_number from tbl_ewi_assembly_part ap left join tbl_ewi_work_instruction wi on ap.ewi_assembly_part_id =  wi.ewi_assembly_part_id where (lifecycle_phase is null or upper(lifecycle_phase) != 'OBSOLETE') and (effective_date is null or (to_char((effective_date at time zone 'America/Los_Angeles'),'YYYYMMDD')  <= to_char((current_timestamp at time zone 'America/Los_Angeles'),'YYYYMMDD'))) and (obsolete_date is null or (to_char((obsolete_date at time zone 'America/Los_Angeles'),'YYYYMMDD')  >= to_char((current_timestamp at time zone 'America/Los_Angeles'),'YYYYMMDD'))) and upper(ap.active_flag) != 'N' and ap.notification_type='EPI' ) assy on ap1.ewi_assembly_part_id = assy.ewi_assembly_part_id ) where myRow between :startRecord and :maxNumberRecords", nativeQuery = true)
//	//List<ErpAssembly> getProcessInstructionAssembliesListByFilter(@Param("startRecord") int startRecord,@Param("maxNumberRecords") int maxNumberRecords);
//	@Query(value="select ewi_assembly_part_id,assembly_number,assembly_revision,created_date from ( select row_number() over ( order by  ap1.updated_date desc ) as myRow, ap1.ewi_assembly_part_id, ap1.assembly_number, ap1.assembly_revision, ap1.created_date from tbl_ewi_assembly_part ap1 inner join ( select distinct ap.ewi_assembly_part_id, ap.assembly_number from tbl_ewi_assembly_part ap left join tbl_ewi_work_instruction wi on ap.ewi_assembly_part_id =  wi.ewi_assembly_part_id where (lifecycle_phase is null or upper(lifecycle_phase) != 'OBSOLETE') and (effective_date is null or (to_char((effective_date at time zone :timeZone),'YYYYMMDD')  <= to_char((current_timestamp at time zone :timeZone),'YYYYMMDD'))) and (obsolete_date is null or (to_char((obsolete_date at time zone :timeZone),'YYYYMMDD')  >= to_char((current_timestamp at time zone :timeZone),'YYYYMMDD'))) and upper(ap.active_flag) != 'N' and ap.notification_type='EPI' and ap.customer_id = :customerId and ap.assembly_number like  :assemblyNumber and ap.erp_company_id = :erpCompanyId ) assy on ap1.ewi_assembly_part_id = assy.ewi_assembly_part_id ) where myRow between :startRecord and :maxNumberRecords", nativeQuery = true)
//	List<ErpAssembly> getProcessInstructionAssembliesListByFilter(@Param("assemblyNumber") String assemblyNumber,@Param("erpCompanyId") int erpCompanyId,@Param("customerId") int customerId, @Param("timeZone") String timeZone,@Param("startRecord") int startRecord,@Param("maxNumberRecords") int maxNumberRecords);

}
